modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "LGPL-3.0"

[[mods]]
modId = "peacefultable"
version = "${version}"
displayName = "Peaceful Table"
authors = "embeddedt"
description = '''
Adds a mob drops block for peaceful players.
'''
#logoFile = ""

[[dependencies.peacefultable]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.peacefultable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.peacefultable]]
modId = "architectury"
mandatory = true
versionRange = "[4.5.76,)"
ordering = "AFTER"
side = "BOTH"